// Real results from openguardrails-bench (seed-v0), generated by harness/run.py.
// Reference detectors + baselines only. OpenGuardrails does NOT submit a detector.
// Third-party vendors (LlamaGuard, Qwen3Guard, hosted APIs) appear once their
// owners run them through a conformant adapter — we do not fabricate their numbers.

export type Row = {
  detector: string;
  type: "model" | "config" | "hybrid" | "baseline";
  injection: number | null;
  malcmd: number | null;
  exfil: number | null;
  secret: number | null;
  macro: number | null;
  note?: string;
};

// macro-F1 ranked, exactly as emitted by the harness.
export const REFERENCE_ROWS: Row[] = [
  { detector: "keyword-baseline", type: "config", injection: 0.421, malcmd: 0.769, exfil: 0.667, secret: 0.588, macro: 0.611, note: "signature-only; high FP, injection F1 just 0.42" },
  { detector: "block-all", type: "baseline", injection: 0.611, malcmd: 0.632, exfil: 0.588, secret: 0.533, macro: 0.591, note: "blocks everything; flattered by a small seed" },
  { detector: "ogr-compose (config⊕llm)", type: "hybrid", injection: 0.9, malcmd: 0.588, exfil: 0.462, secret: 0.4, macro: 0.588 },
  { detector: "config-rules", type: "config", injection: 0.429, malcmd: 0.588, exfil: 0.333, secret: 0.4, macro: 0.438 },
  { detector: "llm-judge (provenance-aware)", type: "model", injection: 0.9, malcmd: 0.286, exfil: 0.333, secret: 0.0, macro: 0.38 },
  { detector: "allow-all", type: "baseline", injection: 0.0, malcmd: 0.0, exfil: 0.0, secret: 0.0, macro: 0.0 },
];

// Vendors invited to submit — shown as pending until they run the suite.
export const PENDING_VENDORS: Row[] = [
  { detector: "LlamaGuard", type: "model", injection: null, malcmd: null, exfil: null, secret: null, macro: null, note: "pending submission" },
  { detector: "Qwen3Guard", type: "model", injection: null, malcmd: null, exfil: null, secret: null, macro: null, note: "pending submission" },
];

export const SEED = {
  version: "seed-v0",
  sizes: "injection 11 · malicious-command 12 · exfil 10 · secret-leak 8 · shared benign 14",
};

export const fmt = (v: number | null) => (v === null ? "—" : v.toFixed(3));
