// Real results from openguardrails-bench (seed-v0), generated by harness/run.py.
// Reference detectors + baselines only. OpenGuardrails does NOT submit a detector.
// Third-party vendors (LlamaGuard, Qwen3Guard, hosted APIs) appear once their
// owners run them through a conformant adapter — we do not fabricate their numbers.

export type Row = {
  detector: string;
  type: "model" | "config" | "hybrid" | "baseline";
  injection: number | null;
  malcmd: number | null;
  exfil: number | null;
  secret: number | null;
  macro: number | null;
  note?: string;
};

// macro-F1 ranked, exactly as emitted by the harness.
export const REFERENCE_ROWS: Row[] = [
  { detector: "keyword-baseline", type: "baseline", injection: 0.4, malcmd: 0.8, exfil: 0.667, secret: 0.667, macro: 0.634, note: "signature-only; high FP, injection F1 just 0.40" },
  { detector: "ogr-compose (config⊕llm)", type: "hybrid", injection: 0.889, malcmd: 0.667, exfil: 0.545, secret: 0.4, macro: 0.625 },
  { detector: "block-all", type: "baseline", injection: 0.625, malcmd: 0.625, exfil: 0.571, secret: 0.571, macro: 0.598 },
  { detector: "config-rules", type: "config", injection: 0.333, malcmd: 0.667, exfil: 0.4, secret: 0.4, macro: 0.45 },
  { detector: "llm-judge (provenance-aware)", type: "model", injection: 0.889, malcmd: 0.333, exfil: 0.4, secret: 0.0, macro: 0.406 },
  { detector: "allow-all", type: "baseline", injection: 0.0, malcmd: 0.0, exfil: 0.0, secret: 0.0, macro: 0.0 },
];

// Vendors invited to submit — shown as pending until they run the suite.
export const PENDING_VENDORS: Row[] = [
  { detector: "LlamaGuard", type: "model", injection: null, malcmd: null, exfil: null, secret: null, macro: null, note: "pending submission" },
  { detector: "Qwen3Guard", type: "model", injection: null, malcmd: null, exfil: null, secret: null, macro: null, note: "pending submission" },
];

export const SEED = {
  version: "seed-v0",
  sizes: "injection 10 · malicious-command 10 · exfil 8 · secret-leak 8 · shared benign 12",
};

export const fmt = (v: number | null) => (v === null ? "—" : v.toFixed(3));
